#include "room_common.h"
#include "room_defs.h"

static const RectF g_room07_platforms[] = {
    { T(0), T(0), T(95), T(3) },
    { T(0), T(3), T(4), T(40) },
    { T(90), T(3), T(5), T(7) },
    { T(5), T(4), T(83), T(2) },
    { T(5), T(6), T(2), T(19) },
    { T(43), T(7), T(2), T(1) },
    { T(64), T(7), T(12), T(1) },
    { T(41), T(8), T(2), T(4) },
    { T(66), T(8), T(5), T(1) },
    { T(73), T(8), T(7), T(1) },
    { T(84), T(8), T(6), T(2) },
    { T(82), T(9), T(2), T(1) },
    { T(16), T(10), T(2), T(1) },
    { T(22), T(10), T(2), T(1) },
    { T(28), T(10), T(13), T(2) },
    { T(83), T(10), T(1), T(29) },
    { T(91), T(10), T(4), T(33) },
    { T(28), T(12), T(1), T(3) },
    { T(46), T(12), T(23), T(2) },
    { T(71), T(12), T(12), T(2) },
    { T(86), T(12), T(2), T(1) },
    { T(69), T(13), T(2), T(1) },
    { T(86), T(13), T(1), T(30) },
    { T(29), T(14), T(18), T(1) },
    { T(82), T(14), T(1), T(25) },
    { T(77), T(17), T(3), T(1) },
    { T(77), T(18), T(1), T(2) },
    { T(7), T(19), T(70), T(1) },
    { T(79), T(19), T(3), T(1) },
    { T(72), T(21), T(7), T(1) },
    { T(12), T(22), T(60), T(1) },
    { T(12), T(23), T(1), T(7) },
    { T(41), T(24), T(2), T(1) },
    { T(63), T(24), T(3), T(1) },
    { T(79), T(24), T(3), T(1) },
    { T(5), T(25), T(1), T(12) },
    { T(20), T(25), T(2), T(1) },
    { T(24), T(25), T(2), T(1) },
    { T(29), T(25), T(2), T(1) },
    { T(36), T(25), T(4), T(1) },
    { T(44), T(25), T(2), T(1) },
    { T(57), T(25), T(4), T(1) },
    { T(68), T(25), T(4), T(1) },
    { T(75), T(25), T(2), T(1) },
    { T(6), T(27), T(1), T(10) },
    { T(15), T(27), T(67), T(2) },
    { T(7), T(28), T(2), T(1) },
    { T(22), T(31), T(35), T(1) },
    { T(22), T(32), T(17), T(5) },
    { T(54), T(32), T(3), T(11) },
    { T(57), T(35), T(7), T(8) },
    { T(22), T(37), T(1), T(6) },
    { T(5), T(39), T(17), T(4) },
    { T(23), T(39), T(16), T(4) },
    { T(4), T(40), T(1), T(3) },
    { T(76), T(40), T(8), T(3) },
    { T(87), T(40), T(4), T(3) },
    { T(84), T(41), T(2), T(2) },
};

static const SpeakerDevice g_room07_speakers[] = {
    DefaultSpeakerAt(T(46), T(32)),
};

static const GravityBoxDef g_room07_gravity_boxes[] = {
    { DefaultGravityBoxAt(T(37.75f), T(37.25f)) },
};

static const PressureSwitchDevice g_room07_pressure_switches[] = {
    { { T(23), T(37), T(1), T(2) }, PRESSURE_SWITCH_MOUNT_LEFT },
    { { T(7), T(27), T(2), T(1) }, PRESSURE_SWITCH_MOUNT_DOWN },
    { { T(69), T(12), T(2), T(1) }, PRESSURE_SWITCH_MOUNT_DOWN },
    { { T(71), T(8), T(2), T(1) }, PRESSURE_SWITCH_MOUNT_UP },
    { { T(7), T(15), T(1), T(2) }, PRESSURE_SWITCH_MOUNT_LEFT },
};

static const PressurePlatformDevice g_room07_pressure_platforms[] = {
    { { T(43), T(8), T(23), T(1) }, T(0), T(0), 1u << 2, 1 },
    { { T(82), T(10), T(1), T(2) }, T(-36), T(0), 1u << 3 },
    { { T(7), T(17), T(5), T(1) }, T(65), T(0), 1u << 4 },
    { { T(6), T(25), T(1), T(2) }, T(2), T(0), 1u << 1 },
    { { T(9), T(28), T(3), T(1) }, T(0), T(0), 1u << 1, 1 },
    { { T(7), T(31), T(15), T(2) }, T(15), T(0), 1u << 1 },
    { { T(5), T(37), T(2), T(2) }, T(0), T(2), 1u << 0 },
};

static const PistonDevice g_room07_pistons[] = {
    { T(4), T(40), T(1), T(1), T(0.90f), T(1), T(32), 0.00f, PISTON_UP },
    { T(84), T(41), T(2), T(1), T(0.90f), T(1), T(27), 0.000f, PISTON_UP },
};



static const WalkerEnemyDef g_room07_walker_enemies[] = {
    { { T(46.25f), T(7.1f), T(1.5f), T(0.9f) }, 100.0f, 1, WALKER_ENEMY_M2 },
    { { T(49.25f), T(7.1f), T(1.5f), T(0.9f) }, 100.0f, 1, WALKER_ENEMY_M2 },
    { { T(52.25f), T(7.1f), T(1.5f), T(0.9f) }, 100.0f, 1, WALKER_ENEMY_M2 },
    { { T(55.25f), T(7.1f), T(1.5f), T(0.9f) }, 100.0f, 1, WALKER_ENEMY_M2 },
    { { T(58.25f), T(7.1f), T(1.5f), T(0.9f) }, 100.0f, 1, WALKER_ENEMY_M2 },
    { { T(61.25f), T(7.1f), T(1.5f), T(0.9f) }, 100.0f, 1, WALKER_ENEMY_M2 },
};

static const RectF g_room07_checkpoints[] = {
    { T(75), T(20), T(1), T(1) },
    { T(22), T(30), T(1), T(1) },
};

static const StaticSpikeDef g_room07_static_spikes[] = {
    StaticSpikeAt(T(90), T(10), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(90), T(11), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(90), T(12), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(87), T(13), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(90), T(13), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(87), T(14), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(90), T(14), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(87), T(15), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(90), T(15), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(87), T(16), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(90), T(16), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(87), T(17), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(90), T(17), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(7), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(8), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(9), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(10), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(11), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(12), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(13), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(14), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(15), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(16), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(17), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(18), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(19), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(20), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(21), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(22), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(23), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(24), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(25), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(26), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(27), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(28), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(29), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(30), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(31), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(32), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(33), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(34), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(35), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(36), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(37), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(38), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(39), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(40), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(41), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(42), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(43), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(44), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(45), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(46), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(47), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(48), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(49), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(50), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(51), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(52), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(53), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(54), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(55), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(56), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(57), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(58), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(59), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(60), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(61), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(62), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(63), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(64), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(65), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(66), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(67), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(68), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(69), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(70), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(71), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(72), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(73), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(74), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(75), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(76), T(18), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(87), T(18), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(90), T(18), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(87), T(19), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(90), T(19), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(7), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(8), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(9), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(10), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(11), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(12), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(13), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(14), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(15), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(16), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(17), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(18), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(19), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(20), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(21), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(22), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(23), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(24), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(25), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(26), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(27), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(28), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(29), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(30), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(31), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(32), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(33), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(34), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(35), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(36), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(37), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(38), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(39), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(40), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(41), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(42), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(43), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(44), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(45), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(46), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(47), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(48), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(49), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(50), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(51), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(52), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(53), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(54), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(55), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(56), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(57), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(58), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(59), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(60), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(61), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(62), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(63), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(64), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(65), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(66), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(67), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(68), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(69), T(20), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(87), T(20), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(90), T(20), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(87), T(21), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(90), T(21), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(87), T(22), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(90), T(22), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(49), T(23), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(50), T(23), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(51), T(23), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(52), T(23), STATIC_SPIKE_ROTATION_180_DEGREES),
    StaticSpikeAt(T(87), T(23), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(90), T(23), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(87), T(24), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(90), T(24), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(87), T(25), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(90), T(25), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(20), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(21), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(22), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(23), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(24), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(25), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(26), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(27), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(28), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(29), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(30), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(31), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(32), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(33), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(34), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(35), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(36), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(37), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(38), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(39), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(40), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(41), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(42), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(43), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(44), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(45), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(46), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(54), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(55), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(56), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(57), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(58), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(59), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(60), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(61), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(62), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(63), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(64), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(65), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(66), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(67), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(68), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(69), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(70), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(71), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(72), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(73), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(74), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(75), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(76), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(77), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(78), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(79), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(80), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(81), T(26), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(87), T(26), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(90), T(26), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(87), T(27), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(90), T(27), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(87), T(28), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(90), T(28), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(87), T(29), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(90), T(29), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(87), T(30), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(90), T(30), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(87), T(31), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(90), T(31), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(87), T(32), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(90), T(32), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(87), T(33), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(90), T(33), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(87), T(34), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(90), T(34), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(87), T(35), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(90), T(35), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(87), T(36), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(90), T(36), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(87), T(37), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(90), T(37), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(87), T(38), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(90), T(38), STATIC_SPIKE_ROTATION_270_DEGREES),
    StaticSpikeAt(T(87), T(39), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(90), T(39), STATIC_SPIKE_ROTATION_270_DEGREES),
};

static const RectF g_room07_type_a_walls[] = {
    { T(80), T(17), T(2), T(1) },
    { T(26), T(23), T(1), T(2) },
    { T(31), T(25), T(2), T(1) },
};

extern const RoomDef g_room07 = {
    g_room07_platforms,
    (int)(sizeof(g_room07_platforms) / sizeof(g_room07_platforms[0])),
    g_room07_type_a_walls,
    (int)(sizeof(g_room07_type_a_walls) / sizeof(g_room07_type_a_walls[0])),
    g_room07_speakers,
    (int)(sizeof(g_room07_speakers) / sizeof(g_room07_speakers[0])),
    { T(88), T(38), T(2), T(2) }, T(14), T(38), { T(0), T(0), T(95), T(43) },
    T(4),
    GRAVITY_DOWN,
    kDefaultDeleteState,
    g_room07_pistons,
    (int)(sizeof(g_room07_pistons) / sizeof(g_room07_pistons[0])),
    g_room07_gravity_boxes,
    (int)(sizeof(g_room07_gravity_boxes) / sizeof(g_room07_gravity_boxes[0])),
    g_room07_pressure_switches,
    (int)(sizeof(g_room07_pressure_switches) / sizeof(g_room07_pressure_switches[0])),
    g_room07_pressure_platforms,
    (int)(sizeof(g_room07_pressure_platforms) / sizeof(g_room07_pressure_platforms[0])),
    0, g_room07_walker_enemies,
    (int)(sizeof(g_room07_walker_enemies) / sizeof(g_room07_walker_enemies[0])), 0, { T(75), T(20), T(1), T(1) }, g_room07_checkpoints, (int)(sizeof(g_room07_checkpoints) / sizeof(g_room07_checkpoints[0])),
    g_room07_static_spikes,
    (int)(sizeof(g_room07_static_spikes) / sizeof(g_room07_static_spikes[0])),
};
