#include "room_common.h"
#include "room_defs.h"

static const RectF g_room08_platforms[] = {
    { T(39), T(0), T(59), T(1) },
    { T(39), T(1), T(1), T(11) },
    { T(68), T(1), T(1), T(6) },
    { T(97), T(1), T(1), T(26) },
    { T(95), T(3), T(2), T(1) },
    { T(47), T(5), T(3), T(1) },
    { T(66), T(10), T(15), T(1) },
    { T(66), T(13), T(1), T(1) },
    { T(39), T(14), T(1), T(13) },
    { T(20), T(16), T(4), T(1) },
    { T(67), T(16), T(24), T(1) },
    { T(40), T(17), T(2), T(1) },
    { T(41), T(18), T(1), T(3) },
    { T(0), T(20), T(6), T(1) },
    { T(8), T(22), T(2), T(1) },
    { T(13), T(22), T(1), T(5) },
    { T(0), T(25), T(13), T(2) },
    { T(14), T(25), T(3), T(2) },
    { T(40), T(25), T(57), T(2) },
};

static const RectF g_room08_type_a_walls[] = {
    { T(94), T(3), T(1), T(1) },
    { T(50), T(6), T(18), T(1) },
    { T(32), T(19), T(2), T(1) },
    { T(27), T(20), T(3), T(1) },
    { T(42), T(20), T(2), T(1) },
    { T(34), T(21), T(3), T(1) },
};

static const PistonDevice g_room08_pistons[] = {
    { T(94), T(20), T(3), T(1), T(0.90f), T(1.00f), T(14), 0.440f, PISTON_UP },
    { T(44), T(23), T(3), T(1), T(0.90f), T(1.00f), T(18), 0.00f, PISTON_UP },
    { T(17), T(27), T(3), T(1), T(0.90f), T(1.00f), T(10), 0.00f, PISTON_UP },
    { T(37), T(27), T(2), T(1), T(0.90f), T(1.00f), T(12), 0.00f, PISTON_UP },
};



static const WalkerEnemyDef g_room08_walker_enemies[] = {
    { { T(73.25f), T(15.1f), T(1.5f), T(0.9f) }, 140.0f, 1, WALKER_ENEMY_M1 },
    { { T(83.25f), T(15.1f), T(1.5f), T(0.9f) }, 140.0f, 1, WALKER_ENEMY_M1 },
    { { T(2.25f), T(19.1f), T(1.5f), T(0.9f) }, 100.0f, 1, WALKER_ENEMY_M2 },
};

static const StaticSpikeDef g_room08_static_spikes[] = {
    StaticSpikeAt(T(67), T(9), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(68), T(9), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(69), T(9), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(70), T(9), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(71), T(9), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(72), T(9), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(73), T(9), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(74), T(9), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(75), T(9), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(76), T(9), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(77), T(9), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(78), T(9), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(79), T(9), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(80), T(9), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(67), T(15), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(90), T(15), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(0), T(21), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(0), T(22), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(0), T(23), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(0), T(24), STATIC_SPIKE_ROTATION_90_DEGREES),
    StaticSpikeAt(T(40), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(41), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(42), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(43), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(44), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(45), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(46), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(47), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(48), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(49), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(50), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(51), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(52), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(53), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(54), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(55), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(56), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(57), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(58), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(59), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(60), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(61), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(62), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(63), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(64), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(65), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(66), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(67), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(68), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(69), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(70), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(71), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(72), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(73), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(74), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(75), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(76), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(77), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(78), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(79), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(80), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(81), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(82), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(83), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(84), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(85), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(86), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(87), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(88), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(89), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(90), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(91), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(92), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(93), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(94), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(95), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
    StaticSpikeAt(T(96), T(24), STATIC_SPIKE_ROTATION_0_DEGREES),
};

extern const RoomDef g_room08 = {
    g_room08_platforms,
    (int)(sizeof(g_room08_platforms) / sizeof(g_room08_platforms[0])),
    g_room08_type_a_walls,
    (int)(sizeof(g_room08_type_a_walls) / sizeof(g_room08_type_a_walls[0])),
    0,
    0,
    { T(95), T(1), T(2), T(2) }, T(5), T(24), { T(0), T(0), T(98), T(27) },
    T(4),
    GRAVITY_DOWN,
    kDefaultDeleteState,
    g_room08_pistons,
    (int)(sizeof(g_room08_pistons) / sizeof(g_room08_pistons[0])),
    0,
    0,
    0, 0,
    0, 0,
    0,
    g_room08_walker_enemies,
    (int)(sizeof(g_room08_walker_enemies) / sizeof(g_room08_walker_enemies[0])),
    0,
    {},
    0,
    0,
    g_room08_static_spikes,
    (int)(sizeof(g_room08_static_spikes) / sizeof(g_room08_static_spikes[0])),
};
